/**
 * ============================================================================
 *  Identity_v1.js — Mappa di Identita Utente
 * ============================================================================
 *  v1.0.0 (2026-05-26)
 *
 *  Sistema di profilazione tematica e territoriale per utenti registrati.
 *  Ogni utente ha una mappa identitaria con:
 *  - 10 dimensioni Matrix (D1-D10) attivabili
 *  - Ambito territoriale (nazionale/locale + regione)
 *  - Flag notifica solo match
 *
 *  La mappa viene generata automaticamente dal Matrix o configurata
 *  manualmente dall'utente nella sua area personale.
 *
 *  Funzioni pubbliche (frontend google.script.run):
 *    getUserIdentity(email)                — legge mappa identita
 *    updateUserIdentity(email, mapJson)    — aggiorna mappa identita
 *    generateIdentityFromMatrix(email)     — genera mappa dai risultati Matrix
 *    getFilteredContent(email, tipo, limit)— bandi/news filtrati per identita
 *
 *  Prefisso: _ident*
 * ============================================================================
 */

// ============================================================================
// SCHEMA MAPPA IDENTITA
// ============================================================================

/**
 * Struttura JSON IdentityMap:
 * {
 *   dims: { D1: true, D2: false, D3: false, D4: true, ... D10: false },
 *   ambito: "nazionale" | "locale",
 *   regione: "" | "Puglia" | "Toscana" | ...
 *   notifyOnlyMatches: false,
 *   autoGenerated: false,
 *   lastUpdate: "2026-05-26T10:30:00Z"
 * }
 */

var IDENT_COL_NAME = 'IdentityMap';
var IDENT_DEFAULT = {
  dims: { D1: false, D2: false, D3: false, D4: false, D5: false, D6: false, D7: false, D8: false, D9: false, D10: false },
  ambito: 'nazionale',
  regione: '',
  notifyOnlyMatches: false,
  autoGenerated: false,
  lastUpdate: ''
};

// Mapping dimensioni → ambiti OC (da Constants.js matrixDims)
var IDENT_DIM_TO_AMBITI = {
  D1: [1],       // Brand & Identity → Amb.1
  D2: [3],       // Collection & Heritage → Amb.3
  D3: [3],       // Facility → Amb.3
  D4: [3],       // Program → Amb.3
  D5: [3],       // Service → Amb.3
  D6: [5],       // Digital → Amb.5
  D7: [2],       // Accessibilita → Amb.2
  D8: [1, 4],    // Audience → Amb.1 + Amb.4
  D9: [5],       // Governance → Amb.5
  D10: [4]       // Welfare → Amb.4
};

var IDENT_REGIONI = [
  'Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Emilia-Romagna',
  'Friuli-Venezia Giulia', 'Lazio', 'Liguria', 'Lombardia', 'Marche',
  'Molise', 'Piemonte', 'Puglia', 'Sardegna', 'Sicilia',
  'Toscana', 'Trentino-Alto Adige', 'Umbria', "Valle d'Aosta", 'Veneto'
];

// Nomi dimensioni per la UI
var IDENT_DIM_NAMES = {
  D1:  'Brand & Identity',
  D2:  'Collection & Heritage',
  D3:  'Facility & Spatial Experience',
  D4:  'Program & Cultural Offer',
  D5:  'Service & Third Place',
  D6:  'Digital Maturity & Tech',
  D7:  'Accessibilita Radicale',
  D8:  'Audience & Edutainment',
  D9:  'Governance & Sustainability',
  D10: 'Welfare Culturale & Impatto'
};

// ============================================================================
// API PUBBLICA
// ============================================================================

/**
 * Legge la mappa identita di un utente.
 * Chiamata dal frontend: google.script.run.getUserIdentity(email)
 */
function getUserIdentity(email) {
  if (!email) return { ok: false, error: 'email mancante' };
  email = String(email).toLowerCase().trim();

  try {
    var sh = _identGetUtentiSheet_();
    if (!sh) return { ok: false, error: 'foglio Utenti non trovato' };

    var iMap = _identEnsureColumn_(sh);
    var headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
    var iEmail = headers.indexOf('Email');
    if (iEmail < 0) return { ok: false, error: 'colonna Email non trovata' };

    var data = sh.getDataRange().getValues();
    for (var r = 1; r < data.length; r++) {
      if (String(data[r][iEmail] || '').toLowerCase().trim() === email) {
        var raw = data[r][iMap] || '';
        var map = raw ? JSON.parse(raw) : JSON.parse(JSON.stringify(IDENT_DEFAULT));
        // Arricchisci con metadata
        map._dimNames = IDENT_DIM_NAMES;
        map._regioni = IDENT_REGIONI;
        map._dimToAmbiti = IDENT_DIM_TO_AMBITI;
        map._activeDims = [];
        map._activeAmbiti = [];
        for (var d in map.dims) {
          if (map.dims[d]) {
            map._activeDims.push(d);
            (IDENT_DIM_TO_AMBITI[d] || []).forEach(function(a) {
              if (map._activeAmbiti.indexOf(a) < 0) map._activeAmbiti.push(a);
            });
          }
        }
        map._hasIdentity = map._activeDims.length > 0;
        return { ok: true, identity: map };
      }
    }
    return { ok: false, error: 'utente non trovato' };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

/**
 * Aggiorna la mappa identita.
 * mapJson = { dims: {D1:true,...}, ambito:'locale', regione:'Puglia', notifyOnlyMatches:false }
 */
function updateUserIdentity(email, mapJson) {
  if (!email) return { ok: false, error: 'email mancante' };
  email = String(email).toLowerCase().trim();

  try {
    var sh = _identGetUtentiSheet_();
    if (!sh) return { ok: false, error: 'foglio Utenti non trovato' };

    var iMap = _identEnsureColumn_(sh);
    var headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
    var iEmail = headers.indexOf('Email');
    if (iEmail < 0) return { ok: false, error: 'colonna Email non trovata' };

    var data = sh.getDataRange().getValues();
    for (var r = 1; r < data.length; r++) {
      if (String(data[r][iEmail] || '').toLowerCase().trim() === email) {
        // Valida e normalizza input
        var map = _identNormalize_(mapJson);
        map.lastUpdate = new Date().toISOString();

        sh.getRange(r + 1, iMap + 1).setValue(JSON.stringify(map));
        Logger.log('[IDENT] Aggiornata identita per ' + email + ': ' + map._activeDimsCount + ' dims attive');
        return { ok: true, identity: map };
      }
    }
    return { ok: false, error: 'utente non trovato' };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

/**
 * Genera mappa identita automaticamente dai risultati Matrix.
 * Attiva le dimensioni dove il punteggio e >= 3 (su scala 1-5).
 */
function generateIdentityFromMatrix(email) {
  if (!email) return { ok: false, error: 'email mancante' };
  email = String(email).toLowerCase().trim();

  try {
    var ss = (typeof getMainSS === 'function') ? getMainSS() : SpreadsheetApp.getActiveSpreadsheet();
    var shResp = ss.getSheetByName('ResponsesMatrix');
    if (!shResp || shResp.getLastRow() < 2) return { ok: false, error: 'Nessuna risposta Matrix trovata' };

    // Cerca la risposta piu recente di questo utente
    // ResponsesMatrix ha response_id, ma il link email e in ContactsMatrix
    var shContacts = ss.getSheetByName('ContactsMatrix');
    var responseId = null;

    if (shContacts && shContacts.getLastRow() >= 2) {
      var cData = shContacts.getDataRange().getValues();
      var cHead = cData[0];
      var iCEmail = -1, iCResp = -1;
      for (var c = 0; c < cHead.length; c++) {
        if (String(cHead[c]).toLowerCase().indexOf('email') >= 0) iCEmail = c;
        if (String(cHead[c]).toLowerCase().indexOf('response') >= 0) iCResp = c;
      }
      if (iCEmail >= 0 && iCResp >= 0) {
        for (var i = cData.length - 1; i >= 1; i--) {
          if (String(cData[i][iCEmail] || '').toLowerCase().trim() === email) {
            responseId = String(cData[i][iCResp] || '');
            break;
          }
        }
      }
    }

    if (!responseId) return { ok: false, error: 'Nessuna compilazione Matrix per ' + email };

    // Leggi punteggi dimensioni dalla risposta
    var rData = shResp.getDataRange().getValues();
    var rHead = rData[0];
    var iRespId = -1, iScoring = -1;
    for (var h = 0; h < rHead.length; h++) {
      if (String(rHead[h]).toLowerCase().indexOf('response_id') >= 0) iRespId = h;
      if (String(rHead[h]).toLowerCase().indexOf('scoring_dimensions') >= 0) iScoring = h;
    }

    if (iRespId < 0 || iScoring < 0) return { ok: false, error: 'Colonne Matrix non trovate' };

    var scores = null;
    for (var j = rData.length - 1; j >= 1; j--) {
      if (String(rData[j][iRespId]) === responseId) {
        try { scores = JSON.parse(rData[j][iScoring]); } catch (_) {}
        break;
      }
    }

    if (!scores) return { ok: false, error: 'Punteggi non trovati per response ' + responseId };

    // Genera mappa: attiva dimensioni con score >= 3 (scala 1-5)
    var map = JSON.parse(JSON.stringify(IDENT_DEFAULT));
    map.autoGenerated = true;

    for (var dim in scores) {
      var key = dim.toUpperCase();
      if (!key.match(/^D\d+$/)) continue;
      var score = parseFloat(scores[dim]);
      if (!isNaN(score) && score >= 3) {
        map.dims[key] = true;
      }
    }

    map.lastUpdate = new Date().toISOString();

    // Salva
    var sh = _identGetUtentiSheet_();
    var iMap = _identEnsureColumn_(sh);
    var headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
    var iEmail = headers.indexOf('Email');
    var data = sh.getDataRange().getValues();
    for (var r = 1; r < data.length; r++) {
      if (String(data[r][iEmail] || '').toLowerCase().trim() === email) {
        sh.getRange(r + 1, iMap + 1).setValue(JSON.stringify(map));
        break;
      }
    }

    var activeDims = Object.keys(map.dims).filter(function(d) { return map.dims[d]; });
    Logger.log('[IDENT] Auto-generata identita per ' + email + ' da Matrix: ' + activeDims.join(', '));
    return { ok: true, identity: map, source: 'matrix', activeDims: activeDims };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

/**
 * Restituisce contenuti (bandi o news) filtrati per la mappa identita dell'utente.
 * tipo: 'bandi' | 'news'
 */
function getFilteredContent(email, tipo, limit) {
  limit = limit || 100;
  if (!email) return { ok: false, error: 'email mancante' };

  var identResult = getUserIdentity(email);
  if (!identResult.ok || !identResult.identity._hasIdentity) {
    // Nessuna identita attiva: restituisci tutto (default)
    return { ok: true, filtered: false, reason: 'no_identity' };
  }

  var identity = identResult.identity;
  var activeAmbiti = identity._activeAmbiti;
  var regione = (identity.ambito === 'locale' && identity.regione) ? identity.regione.toLowerCase() : '';

  try {
    var ss = (typeof getMainSS === 'function') ? getMainSS() : SpreadsheetApp.getActiveSpreadsheet();
    var items = [];

    if (tipo === 'bandi') {
      // Bandi_v5
      var shB = ss.getSheetByName('Bandi_v5');
      if (shB && shB.getLastRow() >= 2) {
        var bData = shB.getDataRange().getValues();
        var bHead = bData[0];
        var iAmb = _findCol_(bHead, 'Ambito');
        var iReg = _findCol_(bHead, 'Regione');
        var iStato = _findCol_(bHead, 'StatoRecord');
        var iTitolo = _findCol_(bHead, 'Titolo');
        var iUrl = _findCol_(bHead, 'UrlBando');

        for (var r = 1; r < bData.length && items.length < limit; r++) {
          if (String(bData[r][iStato] || '') === 'archiviato') continue;

          var ambito = parseInt(bData[r][iAmb]) || 0;
          var bandoRegione = String(bData[r][iReg] || '').toLowerCase();

          // Filtro ambiti
          if (activeAmbiti.length > 0 && activeAmbiti.indexOf(ambito) < 0) continue;
          // Filtro regione
          if (regione && bandoRegione && bandoRegione.indexOf(regione) < 0 && regione.indexOf(bandoRegione) < 0) continue;

          items.push({
            titolo: String(bData[r][iTitolo] || ''),
            url: String(bData[r][iUrl] || ''),
            ambito: ambito,
            regione: String(bData[r][iReg] || '')
          });
        }
      }
    }

    return { ok: true, filtered: true, items: items, activeAmbiti: activeAmbiti, regione: regione || 'tutta Italia' };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

// ============================================================================
// HOOK DIGEST: filtra contenuti per identita nel routing digest
// ============================================================================

/**
 * Restituisce gli ambiti attivi per un utente (usato da Digest_routing.js).
 * Ritorna array di ambiti [1,2,3,4,5] o [] se nessun filtro.
 */
function getIdentityAmbitiForUser(email) {
  if (!email) return [];
  try {
    var result = getUserIdentity(email);
    if (result.ok && result.identity._hasIdentity) {
      return result.identity._activeAmbiti;
    }
  } catch (_) {}
  return []; // nessun filtro
}

/**
 * Restituisce la regione filtro per un utente (usato da Digest_routing.js).
 * Ritorna stringa regione o '' se tutta Italia.
 */
function getIdentityRegioneForUser(email) {
  if (!email) return '';
  try {
    var result = getUserIdentity(email);
    if (result.ok && result.identity.ambito === 'locale' && result.identity.regione) {
      return result.identity.regione;
    }
  } catch (_) {}
  return '';
}

// ============================================================================
// HELPERS INTERNI
// ============================================================================

function _identGetUtentiSheet_() {
  try {
    var ss = (typeof getMainSS === 'function') ? getMainSS() : SpreadsheetApp.getActiveSpreadsheet();
    return ss.getSheetByName(OC_UTENTI_SHEET || 'Utenti');
  } catch (_) { return null; }
}

/**
 * Assicura che la colonna IdentityMap esista nel foglio Utenti.
 * Ritorna l'indice (0-based) della colonna.
 */
function _identEnsureColumn_(sh) {
  var headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
  var idx = headers.indexOf(IDENT_COL_NAME);
  if (idx >= 0) return idx;

  // Aggiungi colonna
  var newCol = sh.getLastColumn() + 1;
  sh.getRange(1, newCol).setValue(IDENT_COL_NAME).setFontWeight('bold');
  Logger.log('[IDENT] Aggiunta colonna ' + IDENT_COL_NAME + ' al foglio Utenti (col ' + newCol + ')');
  return newCol - 1; // 0-based
}

function _identNormalize_(input) {
  var map = JSON.parse(JSON.stringify(IDENT_DEFAULT));

  if (typeof input === 'string') {
    try { input = JSON.parse(input); } catch (_) { return map; }
  }
  if (!input || typeof input !== 'object') return map;

  // Dimensioni
  if (input.dims && typeof input.dims === 'object') {
    for (var d = 1; d <= 10; d++) {
      var key = 'D' + d;
      map.dims[key] = !!(input.dims[key]);
    }
  }

  // Ambito
  if (input.ambito === 'locale') {
    map.ambito = 'locale';
  } else {
    map.ambito = 'nazionale';
  }

  // Regione
  if (input.regione && typeof input.regione === 'string') {
    var reg = input.regione.trim();
    if (IDENT_REGIONI.indexOf(reg) >= 0) {
      map.regione = reg;
    }
  }

  // Notify only matches
  map.notifyOnlyMatches = !!(input.notifyOnlyMatches);

  // Auto-generated flag
  map.autoGenerated = !!(input.autoGenerated);

  // Conteggio per log
  map._activeDimsCount = Object.keys(map.dims).filter(function(d) { return map.dims[d]; }).length;

  return map;
}

function _findCol_(headers, name) {
  for (var i = 0; i < headers.length; i++) {
    if (String(headers[i]).toLowerCase() === name.toLowerCase()) return i;
  }
  return -1;
}

// ============================================================================
// FINE Identity_v1.js
// ============================================================================
